routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();

Route::GET('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::POST('/', 'Auth\LoginController@login');
Route::POST('/logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth', 'userMiddleware']], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/{id}', 'HomeController@view')->name('home.view');

    /*
    * CLUB ADMINISTRATION ROUTE
    */
    Route::resource('club_meetings', 'ClubAdministration\ClubMeetingsController', ['only' => ['index', 'show', 'store']]);
    Route::resource('club_bulletin', 'ClubAdministration\ClubBulletinController', ['only' => ['index', 'show', 'store']]);
    Route::resource('club_participation', 'ClubAdministration\ClubParticipationController', ['only' => ['index', 'show', 'store']]);
    Route::resource('club_registration', 'ClubAdministration\ClubRegistrationController', ['only' => ['index', 'show', 'store']]);

    /*
    * CLUB MEMBERSHIP ROUTE
    */
    Route::resource('membership_classification', 'ClubMembership\MembershipClassificationController', ['only' => ['index', 'show', 'store']]);
    Route::resource('membership_growth', 'ClubMembership\MembershipGrowthController', ['only' => ['index', 'show', 'store']]);
    Route::resource('membership_development', 'ClubMembership\MembershipDevelopmentController', ['only' => ['index', 'show', 'store']]);

    /*
    * SERVICE PROJECT COMMITTEE ROUTE
    */
    Route::resource('water_supply', 'ServiceProjectCommittee\WaterSupplySanitationController', ['only' => ['index', 'show', 'store']]);
    Route::resource('disease_prevention', 'ServiceProjectCommittee\DiseasePreventionController', ['only' => ['index', 'show', 'store']]);
    Route::resource('economic_community', 'ServiceProjectCommittee\EconomicCommunityController', ['only' => ['index', 'show', 'store']]);
    Route::resource('maternal_child', 'ServiceProjectCommittee\MaternalChildController', ['only' => ['index', 'show', 'store']]);
    Route::resource('basic_education', 'ServiceProjectCommittee\BasicEducationController', ['only' => ['index', 'show', 'store']]);
    Route::resource('youth_service', 'ServiceProjectCommittee\YouthServiceController', ['only' => ['index', 'show', 'store']]);

    /*
    * CLUB PUBLIC RELATION COMMITTEE ROUTE
    */
    Route::resource('media_coverage', 'ClubPublicRelationCommittee\MediaCoverageController', ['only' => ['index', 'show', 'store']]);
    Route::resource('club_flagship', 'ClubPublicRelationCommittee\ClubFlagshipController', ['only' => ['index', 'show', 'store']]);
    Route::resource('promotion', 'ClubPublicRelationCommittee\PromotionController', ['only' => ['index', 'show', 'store']]);

    /*
    * THE ROTARY FOUNDATION COMMITTEE ROUTE
    */
    Route::resource('annual_fund', 'RotaryFoundationCommittee\AnnualFundController', ['only' => ['index', 'show', 'store']]);
    Route::resource('participation_in_trf', 'RotaryFoundationCommittee\ParticipationInTRFController', ['only' => ['index', 'show', 'store']]);

    /*
   * FORM PREVIEW
   */
    Route::resource('preview', 'FormPreviewController', ['only' => ['index', 'show']]);
    Route::post('preview/submit', 'FormPreviewController@finalSubmit')->name('final.submit');

});

Route::group(['middleware' => ['auth', 'adminMiddleware']], function () {
    /*
    * ADMIN ROUTE
    */
    Route::get('/admin', 'AdminController@index')->name('admin.home');
    Route::get('/admin/{month_id}/{user_id}', 'AdminController@reportSearch')->name('admin.preview');
    Route::get('/admin/{month_id}', 'AdminController@clubView')->name('admin.club.view');
    Route::post('/admin/mark', 'AdminController@mark')->name('admin.mark');

});

resources/views/pages/admin_preview.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-left">
                        <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                        <li class="breadcrumb-item active">Club lists</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12" style="margin-top: 4px;">
                    <div class="card">
                        <div class="card-header" style="background-color: gainsboro;">
                            <h3 class="card-title">Club Information - {{$month_name->name}}({{count($club)}} records)</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0" style="box-shadow: none !important;">
                            <table class="table table-hover" style="background-color: antiquewhite">
                                <thead>
                                <tr>
                                    <th width="10%" class="text-left">S.N</th>
                                    <th width="30%" class="text-left">Club Name</th>
                                    <th width="10%" class="text-left">Status</th>
                                    <th width="10%" class="text-left">Preview</th>
                                    <th class="text-left">Mark</th>
                                </tr>
                                </thead>
                                <tbody>
                                @php $i = 1; @endphp
                                @foreach($club as $c)
                                    <tr>
                                        <td>{{$i++}}.</td>
                                        <td>{{$c->club_name}}</td>
                                        <td>
                                            @if(\App\Model\Complete::adminClubCheck($month_id, $c->id))
                                                &nbsp; &nbsp;<i class='fas fa-check'></i>
                                            @else
                                                &nbsp; &nbsp;<i class='fas fa-times'></i>
                                            @endif
                                        </td>
                                        <td>
                                            @if(\App\Model\Complete::adminClubCheck($month_id, $c->id))
                                                <a href="{{route('admin.preview', ['month_id' => $month_id, 'user_id' => $c->id])}}">preview</a>
                                            @endif
                                        </td>
                                        <td>
                                            <form method="post" action="{{route('admin.mark')}}">
                                                @csrf
                                                <div class="row">
                                                    <input type="hidden" name="club_id" value="{{$c->id}}"/>
                                                    <input type="hidden" name="month_id" value="{{$month_id}}"/>
                                                    <div class="col-md-10">

                                                        <input type="text" required class="form-control" style="margin: 0; padding: 9px;" value="{{App\Model\AdminMark::getMark($c->id, $month_id)}}" name="mark" />
                                                    </div>
                                                    <div class="col-md-2">
                                                        <button type="submit" class="btn btn-primary mb-2">Save</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/annual_fund.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-left">
                        <li class="breadcrumb-item"><a href="index.blade.php">Home</a></li>
                        <li class="breadcrumb-item active">Annual Fund Contribution</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header card_header p-0">
                            <p class="card-title ml-3"><small>Annual Fund Contribution</small></p>
                        </div>
                        <form class="mt-sm-3 mt-md-0" method="post" action="{{route('annual_fund.store')}}">
                            @csrf
                            <div class="card-body card_body pt-sm-0 pt-md-3 pb-0">
                                <div class="form-row">
                                    <div class="form-group col-xl-4 col-md-12 col-sm-6 mr-auto">
                                        <label for="club_name"><strong>Club Name</strong></label>
                                        <input type="text" readonly class="form-control-plaintext" id="club_name"
                                               value="{{Auth::user()->club_name}}">
                                    </div>
                                    <input type="hidden" name="id" value="{{$annual_fund?($annual_fund->id ? $annual_fund->id : ""):""}}"/>
                                    <input type="hidden" name="month_id" value="{{$month_id}}"/>
                                    <div class="form-group col-xl-4 col-md-12 col-sm-6">
                                        <label for="annual_target"><strong>Annual Target of TRF Contribution (USD):</strong></label>
                                        <input type="text" class="form-control" required name="annual_target" id="annual_target"
                                        value="{{$annual_fund?$annual_fund->annual_target:""}}">
                                    </div>
                                </div>

                                <div class="table-responsive mb-3">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                        <tr>
                                            <th>S.N</th>
                                            <th>TRF Contribution categories</th>
                                            <th>No of contributing Members</th>
                                            <th>Total Amount USD</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>100% Club Contribution: Small Gifts
                                                Minimum USD 10 to USD 99
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="club_contribution_first"
                                                >{{$annual_fund?json_decode($annual_fund->club_contribution)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="club_contribution_second"
                                                >{{$annual_fund?json_decode($annual_fund->club_contribution)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Rotary Foundation Sustaining Members (RFSM):
                                                USD 100 per year
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="rotary_foundation_first"
                                                >{{$annual_fund?json_decode($annual_fund->rotary_foundation)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="rotary_foundation_second"
                                                >{{$annual_fund?json_decode($annual_fund->rotary_foundation)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Paul Harris Fellow (PHF):
                                                USD 300 or USD 500 as directed by the District
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="phf_first"
                                                >{{$annual_fund?json_decode($annual_fund->phf)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="phf_second"
                                                >{{$annual_fund?json_decode($annual_fund->phf)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Multi Paul Harris Fellow (MPHF)
                                                USD 300 or USD 500 as directed by the District
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="mphf_first"
                                                >{{$annual_fund?json_decode($annual_fund->mphf)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="mphf_second"
                                                >{{$annual_fund?json_decode($annual_fund->mphf)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>5.</td>
                                            <td>PAUL HARRIS SOCIETY (PHS)
                                                USD 1000.00 per year
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="phs_first"
                                                >{{$annual_fund?json_decode($annual_fund->phs)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="phs_second"
                                                >{{$annual_fund?json_decode($annual_fund->phs)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>6.</td>
                                            <td>Major Donor
                                                USD 10000.00
                                            </td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="major_donor_first"
                                                >{{$annual_fund?json_decode($annual_fund->major_donor)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="major_donor_second"
                                                >{{$annual_fund?json_decode($annual_fund->major_donor)->second:""}}</textarea></td>
                                        </tr>
                                        <tr>
                                            <td>6.</td>
                                            <td>Others</td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="others_first"
                                                >{{$annual_fund?json_decode($annual_fund->others)->first:""}}</textarea></td>
                                            <td><textarea style="width: 100%; height: 40px;" class="form-control" name="others_second"
                                                >{{$annual_fund?json_decode($annual_fund->others)->second:""}}</textarea></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-white p-0">
                                <div class="form-row float-right p-2 mr-3 ml-3">
                                    <button type="submit" class="btn btn-block btn-primary">Save <i class="fas fa-check"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/club_bulletin.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-left">
                        <li class="breadcrumb-item"><a href="index.blade.php">Home</a></li>
                        <li class="breadcrumb-item active">Club Bulletin</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header card_header p-0">
                            <p class="card-title ml-3"><small>Club Bulletin</small></p>
                        </div>
                        <form class="mt-sm-3 mt-md-0" method="post" action="{{route('club_bulletin.store')}}">
                            @csrf
                            <div class="card-body card_body pt-sm-0 pt-md-3 pb-0">
                                <div class="form-row">
                                    <div class="form-group col-xl-3 col-md-12 col-sm-6">
                                        <label for="club_name"><strong>Club Name</strong></label>
                                        <input type="text" readonly class="form-control-plaintext" id="club_name"
                                               value="{{Auth::user()->club_name}}">
                                    </div>
                                    <input type="hidden" name="id" value="{{$club_bulletins?($club_bulletins->id ? $club_bulletins->id : ""):""}}"/>
                                    <input type="hidden" name="month_id" value="{{$month_id}}"/>
                                    <div class="form-group col-xl-3 col-md-12 col-sm-6">
                                        <label for="members"><strong>Total Number of Members:</strong></label>
                                        <input type="text" required name="no_of_members" class="form-control"
                                               value="{{$club_bulletins?$club_bulletins->no_of_members:""}}" id="members">
                                    </div>
                                    <div class="form-group col-xl-3 col-md-12 col-sm-6">
                                        <label for="attendance"><strong>Club attendance:</strong></label>
                                        <input type="text" class="form-control" id="attendance" name="club_attendance"
                                               value="{{$club_bulletins?$club_bulletins->club_attendance:""}}">
                                    </div>
                                    <div class="form-group col-xl-3 col-md-12 col-sm-6">
                                        <label for="annual_target"><strong>Annual Target of attendance(%):</strong></label>
                                        <input type="text" id="annual_target" class="form-control" name="annual_target_percent"
                                               value="{{$club_bulletins?$club_bulletins->annual_target_percent:""}}">
                                    </div>
                                </div>

                                <div class="table-responsive mb-3">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                        <tr>
{{--                                            <th colspan="6" class="text-left">Title of the Club Bulletin: &nbsp;--}}
{{--                                                <textarea style="height:30px;" class="form-control" name="title">--}}
{{--                                                    {{$club_bulletins?$club_bulletins->title:""}}--}}
{{--                                                </textarea>--}}
{{--                                            </th>--}}
                                            <th colspan="6">
                                                <div class="form-group row mt-2 mb-0">
                                                    <label for="title" class="col-sm-2 col-form-label">Title of the Club Bulletin:</label>
                                                    <div class="col-sm-6">
                                                        <input type="text" name="title" class="form-control" id="title" value="{{$club_bulletins?$club_bulletins->title:""}}">
                                                    </div>
                                                </div>
                                            </th>
                                        </tr>
                                        <tr>
                                            <th rowspan="2"></th>
                                            <th colspan="3">Frequency of publication Published</th>
                                            <th colspan="2">Published in </th>
                                        </tr>
                                        <tr>
                                            <th width="15%">Weekly</th>
                                            <th width="15%">Fortnightly</th>
                                            <th width="15%">Monthly</th>
                                            <th width="15%">Hard Copy</th>
                                            <th width="15%">E-copy</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>No of issues published in this month</td>
{{--                                            <td><textarea style="width: 100%;" class="form-control" name="no_of_issue_first"--}}
{{--                                                >{{$club_bulletins?json_decode($club_bulletins->no_of_issue)->first:""}}</textarea></td>--}}
{{--                                            <td><textarea style="width: 100%;" class="form-control" name="no_of_issue_second"--}}
{{--                                                >{{$club_bulletins?json_decode($club_bulletins->no_of_issue)->second:""}}</textarea></td>--}}
{{--                                            <td><textarea style="width: 100%;" class="form-control" name="no_of_issue_third"--}}
{{--                                                >{{$club_bulletins?json_decode($club_bulletins->no_of_issue)->third:""}}</textarea></td>--}}
{{--                                            <td><textarea style="width: 100%;" class="form-control" name="no_of_issue_fourth"--}}
{{--                                                >{{$club_bulletins?json_decode($club_bulletins->no_of_issue)->fourth:""}}</textarea></td>--}}
{{--                                            <td><textarea style="width: 100%;" class="form-control" name="no_of_issue_fifth"--}}
{{--                                                >{{$club_bulletins?json_decode($club_bulletins->no_of_issue)->fifth:""}}</textarea></td>--}}

                                            <td>
                                                <select class="form-control" name="no_of_issue_first">
                                                    <option value="">Select..</option>
                                                    <option value="Yes" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->first == 'Yes' ? "selected" :"" :"" !!}>YES</option>
                                                    <option value="No" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->first == 'No' ? "selected" :"" :"" !!}>NO</option>
                                                </select>
                                            </td>
                                            <td>
                                                <select class="form-control" name="no_of_issue_second">
                                                    <option value="">Select..</option>
                                                    <option value="Yes" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->second == 'Yes' ? "selected" :"" :"" !!}>YES</option>
                                                    <option value="No" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->second == 'No' ? "selected" :"" :"" !!}>NO</option>
                                                </select>
                                            </td>
                                            <td>
                                                <select class="form-control" name="no_of_issue_third">
                                                    <option value="">Select..</option>
                                                    <option value="Yes" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->third == 'Yes' ? "selected" :"" :"" !!}>YES</option>
                                                    <option value="No" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->third == 'No' ? "selected" :"" :"" !!}>NO</option>
                                                </select>
                                            </td>
                                            <td>
                                                <select class="form-control" name="no_of_issue_fourth">
                                                    <option value="">Select..</option>
                                                    <option value="Yes" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->fourth == 'Yes' ? "selected" :"" :"" !!}>YES</option>
                                                    <option value="No" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->fourth == 'No' ? "selected" :"" :"" !!}>NO</option>
                                                </select>
                                            </td>
                                            <td>
                                                <select class="form-control" name="no_of_issue_fifth">
                                                    <option value="">Select..</option>
                                                    <option value="Yes" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->fifth == 'Yes' ? "selected" :"" :"" !!}>YES</option>
                                                    <option value="No" {!! $club_bulletins?json_decode($club_bulletins->no_of_issue)->fifth == 'No' ? "selected" :"" :"" !!}>NO</option>
                                                </select>
                                            </td>
                                        </tr>
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th colspan="6" class="text-center">Attach e-copies in the monthly report</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="card-footer text-white p-0">
                                <div class="form-row float-right p-2 mr-3 ml-3">
                                    <button type="submit" class="btn btn-block btn-primary">Save <i class="fas fa-check"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Index Page</h2>
</div>
@endsection